# Generated by Django 3.1.4 on 2021-02-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paypal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Plan ')),
                ('paypalPlanId', models.CharField(blank=True, max_length=255, null=True, verbose_name='Paypal Subscripción id')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
            ],
            options={
                'verbose_name': 'Paypal Plan',
                'verbose_name_plural': 'Paypal Plans',
                'ordering': ['-created'],
            },
        ),
    ]
