# Generated by Django 3.1.4 on 2021-02-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210207_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='paypalPlanId',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Paypal Subscripción id'),
        ),
    ]
