# Generated by Django 3.1.4 on 2021-02-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210214_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='active',
            field=models.CharField(choices=[('A', 'Activo'), ('T', 'temporal'), ('C', 'Cancell')], default='C', max_length=1, verbose_name='Status'),
        ),
    ]
