# Generated by Django 3.1.4 on 2021-02-21 23:47

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210214_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='active',
            field=models.CharField(choices=[(users.models.statusChoices['ACTIVE'], 'A'), (users.models.statusChoices['TRIAL'], 'T'), (users.models.statusChoices['CANCELLED'], 'C')], default=users.models.statusChoices['CANCELLED'], max_length=1, verbose_name='Status'),
        ),
    ]
