# Generated by Django 3.1.4 on 2021-03-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210221_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='paypal_cancel_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de cancelación paypal'),
        ),
    ]
