# Generated by Django 3.1.4 on 2021-03-16 02:35

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_profile_paypal_cancel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='active',
            field=models.CharField(choices=[(users.models.statusChoices['ACTIVE'], 'ACTIVO'), (users.models.statusChoices['TRIAL'], 'TEMPORAL'), (users.models.statusChoices['CANCELLED'], 'CANCELADO')], default=users.models.statusChoices['CANCELLED'], max_length=20, verbose_name='Status'),
        ),
    ]
