# Generated by Django 3.2.5 on 2021-08-24 14:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210315_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='YogaClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='class_images/', verbose_name='Imagen')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la clase')),
                ('hour', models.TimeField()),
                ('description', ckeditor.fields.RichTextField(verbose_name='Descripción')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='DayClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('Miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sabado'), ('domingo', 'Domingo')], max_length=50, verbose_name='Día')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('categories', models.ManyToManyField(to='users.YogaClass', verbose_name='clases')),
            ],
        ),
    ]
