# Generated by Django 3.2.5 on 2021-08-27 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_dayclass_yogaclass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yogaclass',
            options={'ordering': ['-created'], 'verbose_name': 'Clase', 'verbose_name_plural': 'Clases de yoga'},
        ),
        migrations.RenameField(
            model_name='dayclass',
            old_name='categories',
            new_name='classes',
        ),
    ]
