# Generated by Django 3.2.5 on 2021-08-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210827_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayclass',
            options={'ordering': ['-created'], 'verbose_name': 'Día de clase', 'verbose_name_plural': 'Días de clases'},
        ),
        migrations.RemoveField(
            model_name='dayclass',
            name='classes',
        ),
        migrations.AddField(
            model_name='yogaclass',
            name='days',
            field=models.ManyToManyField(to='users.DayClass', verbose_name='días de clase'),
        ),
    ]
