# Generated by Django 3.2.5 on 2021-09-07 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20210827_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yogaclass',
            name='days',
        ),
        migrations.DeleteModel(
            name='DayClass',
        ),
        migrations.DeleteModel(
            name='YogaClass',
        ),
    ]
