"""
Django settings for satnam_yoga project.

Generated by 'django-admin startproject' using Django 2.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '9$xjmaxhvb8b-^i(^l#rt^y4vnphw8zk5m2d+kowly=i=gu8s@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #Local apps:
    'ckeditor',
    'users.apps.UsersConfig',
    'videos.apps.VideosConfig',
    'posts',
    'payments.apps.PaymentsConfig',
    'contact',
    'pages.apps.PagesConfig',
    'BruteBuster',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'BruteBuster.middleware.RequestMiddleware',
    'satnam_yoga.middleware.profile_payment_completion_middleware',
    'satnam_yoga.middleware.user_profile_completion_middleware',
    'satnam_yoga.middleware.user_profile_paypal_account_verify_is_active_middleware'
]

ROOT_URLCONF = 'satnam_yoga.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'satnam_yoga.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'NAME': 'dbsatnam',
        'USER': 'dbadmin',
        'PASSWORD': '17063471',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

MEDIA_URL = '/media/'
STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), "static")

STATICFILES_DIRS =[os.path.join(BASE_DIR,"static")]

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# STRIPE
STRIPE_PRICE_ID = "price_1I2kVQJQ5QjlwW1LWRpqDQlC"
STRIPE_PRODUCT_ID = "prod_Ie2atcJCFnE9JN"
STRIPE_PRICE_YEAR_ID = "price_1I0UVAJQ5QjlwW1L7gp17Cpi"
STRIPE_PRODUCT_YEAR_ID = "prod_IbhmBE0npzldsr"
STRIPE_PUBLISHABLE_KEY = 'pk_test_51Hy78jJQ5QjlwW1LlMZylr7CmJh4I4EEt7kaBBXRgnSSRTKjVXPVIzcAz5UcCecrMCQulDqbCtiffR5BbotMLm3Z00ZgMyRVhh'
STRIPE_SECRET_KEY = 'sk_test_51Hy78jJQ5QjlwW1LvaXVjvRE0YteDPEkqhIUPop91IYye5SPKedAXlUQhsy7SBtW6UqfFDoQ1rjQfb2bNOFqIaRp005Ur0AZsm'
STRIPE_ENDPOINT_SECRET  = 'whsec_hLynjuTrDlemhunB8gR8GSizdARAqZCu'

#ckeditor
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
            ['RemoveFormat'],
            ['FontSize'],
            ['Font'],
            ['Format']
        ],
    }
}


#Email Config
EMAIL_HOST = 'smtp.office365.com'
EMAIL_PORT= '587'
EMAIL_HOST_USER= 'satnamyogajal@hotmail.com'
EMAIL_HOST_PASSWORD= 'GuruRattan1319'
EMAIL_USE_TLS= True
DEFAULT_FROM_EMAIL = 'satnamyogajal@hotmail.com'
SERVER_EMAIL = 'satnamyogajal@hotmail.com'
# EMAIL_USE_SSL= False

LOGIN_URL='login'

# PAYPAL INFO
PAYPAL_CLIENT_ID = 'AY86OU5VjDXN_nDheNxF6xVMtK50JnQmA-1SxR8M1TJCj48tk0EYF9-yaqFYFEzhG-o8gjdPvNPYOWRU'
PAYPAL_SECRET_ID = 'EK0__GZD3G68m18l90pankZhHFB7FNd3CKXSjL9Alz6OdISom4iFM85rM5FbC_UX019vtapOmIUfgh7g'
URL_PAYPAL_TOKEN = 'https://api.sandbox.paypal.com/v1/oauth2/token'
PAYPAL_WEEBHOOK_ID ='7CV46257E8172601D'


BB_MAX_FAILURES= 5
BB_BLOCK_INTERVAL= 5

# CRON JOBS
