# Generated by Django 3.1.4 on 2021-02-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210207_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='paypalSubscriptionId',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Paypal Subscripción id'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stripeCustomerId',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Cliente id'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stripeSubscriptionId',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Subscripción id'),
        ),
    ]
