# Generated by Django 3.1.4 on 2021-02-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_paypalplanid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='paypalPlanId',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Paypal plan id'),
        ),
    ]
