# Generated by Django 3.1.4 on 2021-02-15 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210214_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='active',
            field=models.CharField(choices=[('a', 'Activo'), ('t', 'temporal'), ('c', 'Cancelada')], default='cancelled', max_length=50, verbose_name='Status'),
        ),
    ]
