# Generated by Django 3.1.4 on 2021-02-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paypal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypal',
            name='SKU',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SKU'),
        ),
    ]
