# Generated by Django 3.1.4 on 2021-01-11 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('image', models.ImageField(blank=True, upload_to='user_images/', verbose_name='Imagen')),
                ('upload', models.FileField(default='default_value', upload_to='video_uploads/', verbose_name='Archivo')),
                ('description', models.TextField(blank=True, default=None, verbose_name='descripción')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(to='videos.Category', verbose_name='Categorias')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Vídeos',
                'ordering': ['created'],
            },
        ),
    ]
