# Generated by Django 3.1.4 on 2021-01-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='free_seen',
            field=models.BooleanField(default=False, verbose_name='Muestra gratis'),
        ),
    ]
