# Generated by Django 3.1.4 on 2021-01-31 23:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_free_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
    ]
