# Generated by Django 3.1.4 on 2021-04-28 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20210131_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='upload',
            field=models.TextField(verbose_name='Vimeo embeded'),
        ),
    ]
